# Generated by Django 3.0.5 on 2020-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200428_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_mono', models.CharField(max_length=50)),
            ],
        ),
    ]
