# Generated by Django 3.0.5 on 2020-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_customer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_detail',
            name='bill',
            field=models.FileField(blank=True, upload_to='bill/'),
        ),
    ]
