# Generated by Django 3.0.5 on 2020-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_completebill_subbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbill',
            name='bill_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completebill',
            name='bill_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subbill',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subbill',
            name='item_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subbill',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
